### ISSUE TITLE
Wrong / wierd pattern

### ISSUE THREAD

**Issue by hackintoshlover** [jeffeb3/sandify#271] opened 2023-07-24 00:05 UTC
Hi Jeff,
Thanks for the awesome software.
Attached is a zip file containing two .thr files for my scara sand table of radius 370mm.
One file has wiper size 7mm other has wiper size 4mm.
According to my understanding wiper should spiral in or spiral out a design.
But in my case, if i use wiper size 4mm the design spirals out and then spirals back in.
Whereas when i use wiper size 7mm and above, the wiper just spirals half the way.
I really need to use wiper size 4mm with only spiral out function.
Kindly help with the same.

[Wiper.zip](https://github.com/jeffeb3/sandify/files/12140215/Wiper.zip)

**Comment by bobnik** [comment] 2023-10-14 10:55
That's quite strange. In 1.0.0, I cannot reproduce this issue, so I am closing. If you continue to have trouble, please open another issue and attach a .sdf file, thanks.

**Closed by bobnik** 2023-10-14 10:55 UTC
